# Generated by Django 6.0.4 on 2026-04-22 11:21

import src.apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=src.apps.products.models.product_image_upload_path),
        ),
    ]
